### ISSUE TITLE
Version code formula generates a lower number for a later version

### ISSUE THREAD

**Issue by asunar** [apache/cordova-js#167]
The [formula ](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#setting-the-version-code)to set the version code for android, generates a lower number for a later version.

If my math is right
18.8.240 =>181040
18.7.1015 => 181715

This results in App not installed message on android when upgrading.

Thanks.

**Comment by janpio** [comment]
This has nothing to do with cordova-js - closing this issue now.

**Comment by janpio** [comment]
The formula only seems to work for version number parts with 2 numbers, not 3. You might want to report this as a bug at https://github.com/apache/cordova-android/issues
