### ISSUE TITLE
Uniform build

### ISSUE THREAD

**Issue by raphinesse** [apache/cordova-js#169]
It would be nice for `cordova-js` to be platform-independent. While I have not had a closer look at the how and why of the current build strategy, here's an outline of what I imagine:

### Suggestion
- Create a platform-independent build of `cordova-js` before publishing to npm and bundle it in the published package (it's *not* checked into git). My tool of choice for this would be `rollup` at the moment of writing.
- Have platforms require `cordova-js` to include the core bundle in the App HTML. Any platform specific JS is handled in the platform but can make use of the provided core functionality

### Positive effects
- `cordova-js` can be platform agnostic => easier to add new platforms
- switch to modern build tooling (`rollup`)
- Releasing a new version of `cordova-js` can be done independently
- Updating of `cordova-js` in a platform requires only `npm i cordova-js@latest`

I don't have time to look into this right now, but I'd appreciate any feedback on this

---
_Related: #162_

**Comment by janpio** [comment]
If I remember correctly platforms used to have individual implementations of "Cordova" in the beginning. Then the next steps was the big `cordova.js` project, which unified most of it, and I guess the "add platform specific js" bit was a solution that made sense back then.

**Comment by breautek** [comment]
> switch to modern build tooling (rollup)

I would encourage considering `webpack` over `rollup` for bundling any code intended to be consumed by the browser (ie non-node code). They both have a comparable set of capabilities but I find `webpack` more mature and I've had problems with `rollup` in the past with my own projects. However the last time I used rollup was pre 1.0 so they may have gotten better now.

**Comment by erisu** [comment]
If I had to pick between `webpack` or `rollup`, I would go with `rollup`.

I always felt `webpack` was a bit bloated on the output and increased the file size more then what was needed. It also really depends on what we are trying to accomplish.

https://medium.com/jsdownunder/rollup-vs-webpack-javascript-bundling-in-2018-b35758a2268

The information in this article may be out-dated since it was written about a year ago.

One of the main questions to think about when looking at the top highlighted line, from that article, is what is `cordova-js`? A library or an app?

> “Use webpack for apps, and Rollup for libraries”

To me, `cordova-js` is a library that is expected to be bundled in an app, the client ends app. They might use `webpack` for their app...

**Comment by dpogue** [comment]
Definitely a :+1: for Rollup from me. Rollup is a small bundler, Webpack is a larger project with runtime overhead.

**Comment by raphinesse** [comment]
Since creating this issue, I _have_ had a closer look at the how and why of the current build strategy.

My observation was the following: We have a quite custom module bundling process. I don't know if it would be feasible, let alone possible to implement it with an existing module bundler. If it is possible, I'm pretty sure that we would have to write custom plugins for it. That however would mostly annul the biggest pro of using an existing bundler in the first place: having less code to maintain.

That observation had lead me to the conclusion that it would be easiest to just modernize our existing custom build system which I did in #205.

If anyone would still be willing to explore the possibility of using an existing module bundler I can try to provide insight into the current build system and the more special requirements a replacement would have to fulfill.

---

To resolve this issue moving forward, my plan was the following:
1. Publicly export `build-tools/index.js` from the `cordova-js` package
2. Instead of building platform-specific JS files with `coho` and bundle them in the platforms, the platforms can now depend on `cordova-js`, `require` the build-tools and build a`cordova.js` file that includes their platform specific extensions. They would probably do that during creation or preparation of the platform specific project. The code for that could look something like the following:
    ```js
    const path = require('path');
    const { build, collectModules } = require('cordova-js');

    const platformLibRoot = path.join(__dirname, '../..');
    const pkg = require(path.join(platformLibRoot, 'package'));
    const modulePath = path.join(platformLibRoot, 'cordova-js-src');

    // Resolves to a String containing a platform-specific cordova-js build
    module.exports = function buildCordovaJs () {
        return build({
            platformName: pkg.name,
            platformVersion: pkg.version,
            extraModules: collectModules(modulePath)
        });
    };
    ```
3. After all platforms have made the conversion, delete the `coho` code that was triggering the old builds and the grunt jobs in this repo that it called. Then we can also get rid of grunt as a dependency. 

What do you guys think of this plan?
