### ISSUE TITLE
Migrate from jasmine-node to Jasmine 3

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-js#171]
I picked up maintainer responsibility of jasmine-node as a temporary workaround to resolve npm audit issues before the next major release. Now that we are targeting the next major release I think we should migrate from jasmine-node to Jasmine 3, which I think would need some minor changes to the JavaScript.

**Comment by brodybits** [comment]
PR #140 looks like an attempt to migrate to Jasmine (2) almost 2 years ago, does not seem to be working.

I am thinking it may be easiest to migrate away from Grunt before migrating away from jasmine-node.

**Comment by raphinesse** [comment]
I have a local branch with tests driven by Karma on Headless Chrome using Jasmine 3. Needs a bit of work still, but I will open a PR as soon as it's ready.
